name: My First CI/CD Pipeline with Github Actions
on: 
  push:
    branches: [marloncoti-patch-1]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v1

      - name: Hello World
        run: echo hello world from github Actions

      - name: Build Step
        shell: bash
        run: |
          # Replace this with your custom build logic
          echo "Hello World from Github Actions!" > gh.txt
          7z a cicd-workshop-artifact.zip .

